version: '3.5'

services:

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contato_seguro
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network